stages:
  - build
  - push
  - deploy

variables:
  CLUSTER: ""
  HELM_CHART_DIR: "deployment-helm"
  KUBE_NAMESPACE: ""
  DOCKER_IMAGE: "$HARBOR_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  IMAGE_TAG: "latest"
  INGRESS_URL: ""
  APP_RUNNING_PORT: 80

build:
  stage: build
  script:
    - docker build -t "$DOCKER_IMAGE:$IMAGE_TAG" .
  only:
    - deploy
  tags:
    - stable

push:
  stage: push
  script:
    - docker push "$DOCKER_IMAGE:$IMAGE_TAG"
  only:
    - deploy
  tags:
    - stable

deploy:
  stage: deploy
  script:
    - |
      helm upgrade --install ${CI_PROJECT_NAME,,} ./$HELM_CHART_DIR --namespace $KUBE_NAMESPACE \
      --set image.repository="$DOCKER_IMAGE" \
      --set image.tag="$IMAGE_TAG" \
      --set ingress.hosts[0].host="$INGRESS_URL.stage.neuralcompany.team" \
      --set ingress.tls[0].hosts[0]="$INGRESS_URL.stage.neuralcompany.team" \
      --set ingress.tls[0].secretName="$INGRESS_URL-tls" \
      --set service.port="$APP_RUNNING_PORT" \
      --kubeconfig="$CLUSTER"
  only:
    - deploy
  tags:
    - stable
